_editables:
  content:
    image: true
    styles: css/editor.css
    
collections_config:
  2023-Projects:
    path: src/2023-Projects
    add_options:
      - name: Add Project 2

paths:
  dam_uploads: https://res.cloudinary.com/vermilion-mandrill/image/upload/