paths:
  uploads: images/
collections_config: {}
_inputs:
  date:
    type: datetime
    label: time
    instance_value: NOW
    cascade: true
  id:
    type: text
    instance_value: uuid
    cascade: true
  select_test:
    type: select
    options:
      allow_empty: true
      values: collections.projects.id
    cascade: true
_select_data: {}
_structures: {}
_editables:
  image:
    options:
      resize_style: contain
      width: 100
      height: 100
  text:
    _type: text_editable
    italic: true
  block:
    _type: content_editable
    format: p h3
    image_size_attributes: true
    redo: true
    undo: true
  content:
    _type: content_editable
    blockquote: true
    bold: true
    bulletedlist: true
    center: align-center
    code: true
    copyformatting: true
    embed: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    justify: align-justify
    left: align-left
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    right: align-right
    snippet: true
    strike: true
    styles: /css/editor.css
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
data_config: {}
timezone: Pacific/Auckland
